[package]
name = "esp-idf-n-hal-build-support"
version = "0.1.0"
authors = ["Yonas Jongkind"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2"
ex = "^0"
bindgen = "^0"
simple_logger = "^1"
regex = "1"
